language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# no requirements, but simulate what a user would see
install: pip install -e . --use-mirrors
before_script:
  - pip install -q -r requirements-test.txt --use-mirrors
script:
  - nosetests tests/spec.py --with-coverage --cover-package=pyld
after_success:
  - coveralls